# Generated by Django 3.2.6 on 2021-10-03 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_userpostoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostoptions',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
