# Generated by Django 3.2.5 on 2021-09-24 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0006_alter_mood_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mood',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
